#632 : Move stack trace formatting out of Span class
open-telemetry/opentelemetry-php pull request #694
Opened 2022-06-01 13:17 UTC by amber0612

2022-06-01 13:19 UTC, brettmc approved these changes

2022-06-02 09:48 UTC, brettmc commented
Can you sort out signing a CLA please? (We can't accept your contribution without this) And also try to write a unit test for the newly-created class, since code coverage has dropped with this refactor.

2022-06-03 07:17 UTC, amber0612 commented
> Can you sort out signing a CLA please? (We can't accept your contribution without this) And also try to write a unit test for the newly-created class, since code coverage has dropped with this refactor.

Hi Bret, Unit test for formatStackTrace was not written previously. Can u help me with what am i supposed to assert equal for Unit test of the formatStackTrace function. As the function returns String which is stack Trace and string returned will be complex with Line numbers too. Do u have ideas on how to handle unit test for this...

2022-06-03 09:49 UTC, Nevay commented
I would write them as `.phpt` tests to have a clean stacktrace. There is an open issue with PHPUnit adding an additional frame; we can use [run-tests.php](https://github.com/php/php-src/blob/master/run-tests.php) instead (at least for now).

```php
--TEST--
Basic stacktrace format
--FILE--
<?php
use OpenTelemetry\SDK\Common\Util\TracingUtil;

require_once 'vendor/autoload.php';

echo TracingUtil::formatStackTrace(new Exception('message')), "\n";
?>
--EXPECT--
Exception: message
 at main(test_stacktrace_basic.php:6)
```

(I plan on creating a follow-up PR to resolve some issues with the current implementation and could take care of the tests if necessary.)

2022-06-03 10:59 UTC, tidal requested changes

2022-06-03 10:59 UTC, tidal commented on src/SDK/Common/Util/TracingUtil.php
> +class TracingUtil
Could you please rename the class to smth like `StackTraceFormatter` and the method to just `format`, please?

2022-06-03 10:59 UTC, tidal commented on src/SDK/Common/Util/TracingUtil.php
> +        $starter = $seen ? 'Caused by: ' : '';
Could you make `Caused by: ` a constant, please?

2022-06-03 10:59 UTC, tidal commented on src/SDK/Common/Util/TracingUtil.php
> +        if (!$seen) {
Could you please check for a `null` value here, please?

2022-06-03 10:59 UTC, tidal commented on src/SDK/Common/Util/TracingUtil.php
> +            $traceKeyHasFunction = $traceKeyHasClass && array_key_exists('function', $trace[0]);
Could you please male `class`and `function` class constants, please?

2022-06-03 10:59 UTC, tidal commented on src/SDK/Common/Util/TracingUtil.php
> +            $seen[] = "$file:$line";
Could you make this a `sprintf` call, please?

2022-06-03 10:59 UTC, tidal commented on src/SDK/Common/Util/TracingUtil.php
> +            if (!count($trace)) {
Could you please check for a numeric value here, please?

2022-06-03 10:59 UTC, tidal commented on src/SDK/Common/Util/TracingUtil.php
> +            $line = array_key_exists('file', $trace[0]) && array_key_exists('line', $trace[0]) && $trace[0]['line'] ? $trace[0]['line'] : null;
Could you make `line` a class constant, please?

2022-06-03 10:59 UTC, tidal commented on src/SDK/Common/Util/TracingUtil.php
> +        if ($prev) {
Could you check for a type here, please?

2022-06-03 13:12 UTC, tidal commented on src/SDK/Common/Util/TracingUtil.php
> +        if (!$seen) {
Yes

2022-06-03 13:12 UTC, tidal approved these changes

2022-06-03 13:13 UTC, merged