Updates Laravel and Symfony quickstarts
open-telemetry/opentelemetry-php pull request #696
Opened 2022-06-02 08:24 UTC by kishannsangani

Updated laravel and symfony quickstarts to create sample application with OTel PHP SDK integrated.

Partially fixes #678 , #679

2022-06-02 12:49 UTC, bobstrecansky approved these changes

2022-06-02 14:15 UTC, tidal requested changes
This is still patching the front controller and using global states (which is the opposite of best practices)

2022-06-06 10:37 UTC, kishannsangani commented
@tidal Can you help me resolve this PR? What should I do w.r.t. [this](https://github.com/open-telemetry/opentelemetry-php/pull/701) PR?

2022-06-29 13:40 UTC, tidal approved these changes

2022-06-29 13:41 UTC, merged