Incorrect metrics endpoint path
open-telemetry/opentelemetry-php pull request #903
Opened 2022-12-20 22:04 UTC by jlabedo

The path is correctly appended in SpanExporterFactory, but not in MetricExporterFactory

2022-12-20 22:41 UTC, brettmc requested changes
`OtlpUtil::method()` is only for grpc, but you're correct that a value should be appended to the provided endpoint, sometimes.

See what you can make of [the spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/exporter.md#endpoint-urls-for-otlphttp) but I think what's clear is that `OTEL_EXPORTER_OTLP_METRICS_ENDPOINT` should be used as-is for http protocols, but `OTEL_EXPORTER_OTLP_ENDPOINT` should have a path appended.
For gRPC, we append a path for either variable.
Would appending `/v1/metrics` to line 40 be enough?

2023-01-11 13:05 UTC, bobstrecansky commented
@jlabedo - are you still planning on continuing with this work?

2023-02-08 13:08 UTC, bobstrecansky commented
@jlabedo - we are happy to pick up this bug squash if you don't have bandwidth to complete this PR.

2023-02-15 05:27 UTC, brettmc commented
Closing, resolved in another PR

2023-02-15 05:27 UTC, closed without merging