Ensure base64 encoded values can be used as headers from env
open-telemetry/opentelemetry-php pull request #943
Opened 2023-03-25 10:25 UTC by cedricziel

This change instructs explode to extract at most 2 parts.

Given an example value of 
```
OTEL_EXPORTER_OTLP_HEADERS=Authorization=Basic bla64=
```

The config parser would have created the elements, where only two are required. The trailing `=` in base64 headers would then have been effectively discarded, leading to invalid configuration.

2023-03-25 11:50 UTC, brettmc requested changes
LGTM - could you add a test case for this?

2023-03-25 22:09 UTC, cedricziel commented
@brettmc added a test

2023-03-26 09:04 UTC, brettmc approved these changes

2023-03-26 09:22 UTC, brettmc commented
@cedricziel one linting issue to fix (`make style` should do it), then it's good to go.

2023-03-26 09:48 UTC, cedricziel commented on tests/Unit/SDK/Common/Configuration/Parser/MapParserTest.php
> +        ]
```suggestion
        ],
```

2023-03-26 09:49 UTC, cedricziel commented
@brettmc done

2023-03-26 22:16 UTC, merged

2023-03-26 22:17 UTC, brettmc commented
Thanks for your contribution, @cedricziel